### ISSUE TITLE
Documentation on non-Docker install

### ISSUE THREAD

**Issue by s3m1s0n1c** [alexjustesen/speedtest-tracker#568] opened 2023-04-28 09:49 UTC
Great Project...

Is there any install guides us non-docker users?

Thanks
Sonic

**Comment by Itay1787** [comment] 2023-04-28 15:44
+1

**Comment by alexdelprete** [comment] 2023-04-28 18:55
Duplicate of #65

**Comment by alexjustesen** [comment] 2023-04-28 23:48
> Duplicate of #20 and #65

True, at the moment unless you're familiar with running a [Laravel](https://laravel.com/docs/9.x/deployment) application bare metal I wouldn't suggest it.

**Closed by alexjustesen** 2023-04-28 23:48 UTC
