### ISSUE TITLE
Scheduler not working corretly 

### ISSUE THREAD

**Issue by zackmuc** [alexjustesen/speedtest-tracker#1519] opened 2024-06-11 12:07 UTC
**Describe the bug**
I have a hourly scheduler but speedtest do not run every hour (see screenshot)

**To Reproduce**
1. Scheduler set to - SPEEDTEST_SCHEDULE="30 */1 * * *" so it should run every hour at 30mins
2. start the container
3. e.g it runs at 1:30 2:30 5:30 but 3:30 und 4:30 are missing, also there is no failed in the log and 1:30 has number 1 and 3:30 number 2 instead of 3 in the list.
4. 

**Expected behavior**
Should run hourly

**Environment (please complete the following information):**
 Docker Raspberrry pi 4

![grafik](https://github.com/alexjustesen/speedtest-tracker/assets/4520343/1ceef62b-7eb5-4a01-a936-406157c97fcc)

**Comment by alexjustesen** [comment] 2024-06-11 13:15
Was there any container logs during that time frame? It's odd that it didn't run under those two only.

**Comment by Orski174** [comment] 2024-06-11 13:32
I'm Having something similar, the general settings page vanished.

I recreated the container, deleted the image and repulled it, deleted the configs but still nothing.

It happened a few days ago, I was a little busy so didn't pay it too much mind.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/72353018/22d2b7c8-563c-42ed-9a19-c16d703d1ebe)

**Comment by svenvg93** [comment] 2024-06-11 13:34
> I'm Having something similar, the general settings page vanished.
> 
> I recreated the container, deleted the image and repulled it, deleted the configs but still nothing.
> 
> It happened a few days ago, I was a little busy so didn't pay it too much mind. ![image](https://private-user-images.githubusercontent.com/72353018/338603539-22d2b7c8-563c-42ed-9a19-c16d703d1ebe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTMwNzEsIm5iZiI6MTcxODExMjc3MSwicGF0aCI6Ii83MjM1MzAxOC8zMzg2MDM1MzktMjJkMmI3YzgtNTYzYy00MmVkLTlhMTktYzE2ZDcwM2QxZWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEzMzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZjVjN2Q0OGVkOGY0ZDY3NDVmZTYzODFhOTg1NGIxMzZmODNkNWI1OTJjMWUyMTA0NWJmYmNkNTRkZDYwNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZUECDdKtTA3FrI1ErxvnJoYGWLL4KRGxeFOb4V9kA-k)

The settings page is remove in the last release see https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.20.0 for more information.

**Comment by zackmuc** [comment] 2024-06-11 13:56
No there is nothing to see in the logs :( 
`[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
speedtest-tracker: https://github.com/sponsors/alexjustesen

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: v0.20.5-ls29
Build-date: 2024-06-11T11:08:50+00:00
───────────────────────────────────────
    
using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.
`

**Comment by Orski174** [comment] 2024-06-11 14:06
> The settings page is remove in the last release see https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.20.0 for more information.

Sorry!! Should've checked the changelog...

**Comment by svenvg93** [comment] 2024-06-11 14:32
> > The settings page is remove in the last release see https://github.com/alexjustesen/speedtest-tracker/releases/tag/v0.20.0 for more information.
> 
> Sorry!! Should've checked the changelog...

No worries :)

**Comment by alexjustesen** [comment] 2024-06-11 18:55
@zackmuc let's let it run for a few days, let me know if 330 and 430 are the only random times where it doesn't run.

**Comment by alexjustesen** [comment] 2024-06-12 14:00
What are the failure error messages? You can read them on the record.

**Comment by zackmuc** [comment] 2024-06-12 18:55
Configuration - No servers defined (NoServersException)

but the others work ;)

**Comment by alexjustesen** [comment] 2024-06-13 00:24
One of the servers in your list isn't available then: https://docs.speedtest-tracker.dev/help/error-messages#configuration-no-servers-defined-noserversexception.

Run `php artisan app:ookla-list-servers` from `app/www/` to get a new list.

**Comment by alexjustesen** [comment] 2024-06-13 00:30
#1519 will be in the next release, if a server ID was provided it will now write that to the failed result record.

**Comment by MacLemon** [comment] 2024-06-13 16:31
Adding another data point:
- Since 2024-06-08 hourly scheduled tests haven't been run at all.
- Triggering manual tests still works fine

Automated hourly was the default as my deployment didn't set an explicit `SPEEDTEST_SCHEDULE` string.

Version: 0.20.6

**Comment by svenvg93** [comment] 2024-06-13 17:38
@zackmuc Do you have the servers defined in `SPEEDTEST_SERVERS` ? if not can you try to set for example the DT server, just to see if the schedule works. Im wondering if it's related to the auto server selection.

**Comment by zackmuc** [comment] 2024-06-13 20:25
@svenvg93  of course i did here from my docker compose file:

`environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - APP_KEY=base64:ZbPPNJ2cJ601f6jQp9GVAsI5fZAuX0idsgxWAKJhcY=
      - DB_CONNECTION=sqlite
      - DB_HOST= #optional
      - DB_PORT= #optional
      - DB_DATABASE= #optional
      - DB_USERNAME= #optional
      - DB_PASSWORD= #optional
      - DISPLAY_TIMEZONE=Europe/Berlin #optional
      - SPEEDTEST_SCHEDULE="30 */1 * * *" # can be represented as a cron schedule same as before.
      - SPEEDTEST_SERVERS= 5662,31470,37516,5214,45865# you can add one or many servers separated by a comma (i.e. "123456,654321,987654").
      - PRUNE_RESULTS_OLDER_THAN=0 #optional
      - DATETIME_FORMAT="j.M.Y, G:i:s"
      - CHART_DATETIME_FORMAT="j.M, G:i:s"
      - APP_DEBUG=true`

**Comment by svenvg93** [comment] 2024-06-13 21:33
@zackmuc Its not mandatory to set it, wanted to rules something out 😉 
Looking at the set servers and your list only the 5214 and 45865 never show up in the list with a completed test. 
For 45865 can you remove the `#`  behind it. Now it will be passed with the id in the test which might cause problems.  
For 5214 the server does not exist anymore. Im getting an error on it as well when testing with the speedtest CLI 

```
speedtest -s 5214
[error] Configuration - No servers defined (NoServersException)
```

**Comment by ds2288** [comment] 2024-06-20 08:22
Why is the settings page gone? Seems unnecessarily difficult to setup now to be honest. Was working perfectly prior to this update.

**Comment by svenvg93** [comment] 2024-06-20 08:51
> Why is the settings page gone? Seems unnecessarily difficult to setup now to be honest. Was working perfectly prior to this update.

See the comment from Alex here https://github.com/alexjustesen/speedtest-tracker/discussions/1470#discussioncomment-9701663

**Comment by TheGroundZero** [comment] 2024-06-21 09:48
>     1. Scheduler set to - SPEEDTEST_SCHEDULE="30 */1 * * *" so it should run every hour at 30mins

To run every hour at `xx:30` you can use an `*` at the hour section (so `30 * * * *`).

But I noticed e.g. `/6` or `1/6` won't work to schedule every 6 hours (starting at 00:00 or 01:00 respectively).
It does work when you do `0-23/6`.
If your cron syntax fails to be parsed, you'll get a 500 error. Enabling debug will show you that error is caused by a _faulty_ cron syntax.

**Comment by alexjustesen** [comment] 2024-06-22 22:32
Closing, looks like this is solved.

**Closed by alexjustesen** 2024-06-22 22:32 UTC
Labels: ❓ question
