### ISSUE TITLE
Daily overview - average Download/Upload/Ping

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [alexjustesen/speedtest-tracker#471] opened 2023-03-11 12:09 UTC
From https://github.com/henrywhitaker3/Speedtest-Tracker I'm missing the daily average overview I'm getting with my telegram bot:

![image](https://user-images.githubusercontent.com/3938423/224483533-e024f150-da91-460b-bf9a-d52be52a20d1.png)

Would be neat if it were implemented. 24hrs, every hour a test, after 24h average is sent. I can work around it, right now, by just having 1 test every 24hrs and then sent to the telegram channel, but that's not what I need.

**Comment by alexjustesen** [comment] 2023-03-11 13:29
Duplicate of #328

**Closed by alexjustesen** 2023-03-11 13:29 UTC
