### ISSUE TITLE
Started not Completed

### ISSUE THREAD

**Issue by mcdoubleyou** [alexjustesen/speedtest-tracker#1591] opened 2024-07-02 14:50 UTC
**Describe the bug**
Most time I didn't get a Completed

**To Reproduce**
Results show Started but nearly no Completed

**Expected behavior**
the other speedtracker works, so it shouldn't my enviroment

**Environment (please complete the following information):**
Debain 12

**Screenshots**
I cloud provide one, but there is simply no Completed

**Logs**
If you tell me where I could find them, maybe I could figure out what's happend

Thanks!

**Comment by svenvg93** [comment] 2024-07-02 19:41
Hi @mcdoubleyou , 

I assume that you see the "Started" in the results table right? 
Can you share your docker compose file, might help us why this is happening

**Comment by mcdoubleyou** [comment] 2024-07-03 15:21
Hey @svenvg93,

yes, thats right.
Here is my compose file - thx for helping!
AppKey censored, not sure if it is unique.

`services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    hostname: speedtest-tracker
    domainname: xins.eu
    #    ports:
    #      - 7080:80
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
      - DB_CONNECTION=sqlite
      - APP_KEY=base64:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - SPEEDTEST_SERVERS=515,8314
      - SPEEDTEST_SCHEDULE=0 * * * *
    volumes:
      - speedtest-tracker_data:/config
    restart: unless-stopped
volumes:
  speedtest-tracker_data:
    external: true
networks:
  proxy:
    external: true`

**Comment by svenvg93** [comment] 2024-07-03 16:41
The problem is that both server set, don't exist anymore. For now the error that is giving by the Speedtest CLI is not handled nicely, hence why the test keeps stuck at `Started`. If you pick other server im sure it will work as expected :) 

<img width="546" alt="Scherm­afbeelding 2024-07-03 om 18 39 25" src="https://github.com/alexjustesen/speedtest-tracker/assets/4511676/b5417367-548a-43fd-95cd-ccfd6794e2f0">

**Comment by alexjustesen** [comment] 2024-07-04 11:36
I'll look into why this isn't being handled correctly when a server is no longer available. It should correctly fail the test if the CLI fails.

**Comment by Nickleaton** [comment] 2024-07-09 20:55
I get the same. If you need a tester...

**Comment by mcdoubleyou** [comment] 2024-07-11 15:56
I deleted the servers but is still fails, then I see there was an update.
looks like it is working after the newst update - I will update after some scheduled tests
thx

my actual yaml

```
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    hostname: speedtest-tracker
    #    ports:
    #      - 7080:80
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - APP_TIMEZONE=Europe/Vienna
      - DISPLAY_TIMEZONE=Europe/Vienna
      - DB_CONNECTION=sqlite
      - APP_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - SPEEDTEST_SERVERS=
      - SPEEDTEST_SCHEDULE=0 * * * *
    volumes:
      - speedtest-tracker_data:/config
    restart: unless-stopped
volumes:
  speedtest-tracker_data:
    external: true
networks:
  proxy:
    external: true
```

**Comment by RobertD502** [comment] 2024-07-11 17:25
Is it possible to have it iterate through the list (if multiple servers are defined) and only fail if none of the user-defined servers exist?

**Comment by mcdoubleyou** [comment] 2024-07-15 17:06
still works, if it keeps running I could delete the other speed tracker in a few days - nice!
thx!

**Comment by bibinvargheset** [comment] 2024-07-17 14:04
It seems it  fails when server list is configured even with the server that is  automatically selected without the selection list

The schedule fails inter, intermittently.

`version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000

            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE='*/15 * * * *'
            - CHART_DATETIME_FORMAT= 'Y-m-d H:i'
            - DATETIME_FORMAT='Y-m-d H:i'
            - APP_TIMEZONE='Asia/Kolkata'
            - DISPLAY_TIMEZONE='Asia/Kolkata'
            - SPEEDTEST_SERVERS=14922,10969,62235,29372 
        volumes:
            - ./:/config
           # - /path/to-custom-ssl-keys:/config/keys
        image: lscr.io/linuxserver/speedtest-tracker:0.20.6  #0.20.6 #latest
        restart: unless-stopped

**Comment by RobertD502** [comment] 2024-07-17 17:55
> It seems it fails when server list is configured even with the server that is automatically selected without the selection list
> 
> The schedule fails inter, intermittently.
> 
> `version: '3.3' services: speedtest-tracker: container_name: speedtest-tracker ports: - 8080:80 - 8443:443 environment: - PUID=1000 - PGID=1000
> 
> ```
>         - DB_CONNECTION=sqlite
>         - SPEEDTEST_SCHEDULE='*/15 * * * *'
>         - CHART_DATETIME_FORMAT= 'Y-m-d H:i'
>         - DATETIME_FORMAT='Y-m-d H:i'
>         - APP_TIMEZONE='Asia/Kolkata'
>         - DISPLAY_TIMEZONE='Asia/Kolkata'
>         - SPEEDTEST_SERVERS=14922,10969,62235,29372 
>     volumes:
>         - ./:/config
>        # - /path/to-custom-ssl-keys:/config/keys
>     image: lscr.io/linuxserver/speedtest-tracker:0.20.6  #0.20.6 #latest
>     restart: unless-stopped
> ```

Check your logs. The server that it attempted to use likely isn't available anymore, which results in a test failing (the test being listed in the results table as "Started"). The reason it is intermittent: successful results happen when a server (from your defined list of servers) that exists is used.

For example:
Let's say I have defined speedtest servers #1, #2, #3, and #4.
Let's also say that servers #3 and #4 existed when I made the configuration, but they no longer exist now.

During my first test, server #1 is used and I see a successful result. However, during the next speedtest server #3 is used and it fails (since the server isn't recognized as an available server anymore by Ookla). During the 3rd test, speedtest-tracker then uses server #2. Once again, I see a successful test result.

A scenario such as this will make it appear as an intermittent issue - it all depends on what server was used, from your defined list of servers, and if the server used exists anymore.

**Comment by svenvg93** [comment] 2024-07-18 09:31
Too add to @RobertD502 explanation, in the case of @bibinvargheset is the second server id that does not exist anymore 

```
speedtest -s 10969
[error] Configuration - No servers defined (NoServersException)
```

**Comment by mircsicz** [comment] 2024-08-09 08:27
Same here, following config doesn't get any further than 'Started'

```
---
# https://github.com/docker/roadmap/issues/658
version: '3.4'
services:
  speedtest-tracker:
    container_name: speedtest
    # ports:
    #  - 127.0.0.1:8081:80
    environment:
      - PORT=80
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=sqlite
      - APP_TIMEZONE=Europe/Berlin
      - DISPLAY_TIMEZONE=Europe/Berlin
      - APP_KEY=base64:SE9KCcRGkNhWov99uLXW91UZRdNP7D4Bm968GQB8BPI=
      - SPEEDTEST_SCHEDULE='*/15 0-23 * * *'
      - SPEEDTEST_SERVERS=52770,44081
      - PRUNE_RESULTS_OLDER_THAN=95
    volumes:
      - /srv/docker/speedtest-techni/config:/config
      # - /path/to-custom-ssl-keys:/config/keys
    image: lscr.io/linuxserver/speedtest-tracker:latest
    platform: "linux/arm64"
    restart: unless-stopped
    networks:
      eth0:
        ipv4_address: 10.10.xxx.91

networks:
  eth0:
    external: true
    name: XXX-BH_SRV_eth0
```

**Comment by RobertD502** [comment] 2024-08-09 15:42
@mircsicz That is because neither of those 2 servers you defined exist.

Output from a manual test using speedtest cli:

```
ERROR: No matched servers: 52770
```
```
ERROR: No matched servers: 44081
```

**Comment by mircsicz** [comment] 2024-08-09 15:48
But both of them were listed using the defined docker cmd...

Which would also describe why even without parameters in the list it doesn't get beyond 'Started'... As the search returns inactive / unavailable servers!

**Comment by RobertD502** [comment] 2024-08-09 15:54
> But both of them were listed using the defined docker cmd...
> 
> Which would also describe why even without parameters in the list it doesn't get beyond 'Started'... As the search returns inactive / unavailable servers!

Without parameters it'll never work since the requirement of defining servers was introduced a few releases ago.

Does the docker command still list those two servers as of today? I've found that some servers may be listed one day and then are unavailable for a while until they return (I've mainly seen this with Spectrum servers). The solution, in the meantime, is to look for and use servers that you find are always available.

**Comment by mircsicz** [comment] 2024-08-09 16:44
I ran the 'docker exec' line like an hour before I posted to this issue 😉

**Comment by RobertD502** [comment] 2024-08-09 17:10
> I ran the 'docker exec' line like an hour before I posted to this issue 😉

Doesn't seem that command is listed in the documentation anymore (perhaps it returned inaccurate results?). Doc now tell you to navigate to `https://c.speedtest.net/speedtest-servers-static.php` to view a list of best servers near you. Regardless of all of that, the reason your speedtests aren't working with your current config is because they are no longer valid servers, as determined by Ookla. Use the link provided to get some server ids to edit your config with.

**Comment by RobertD502** [comment] 2024-08-13 19:15
@alexjustesen I was referring to your own documentation - If I recall correctly, it had previously mentioned a command to execute within the container which showed nearby servers, but now it shows:

![image](https://github.com/user-attachments/assets/a24ae4fa-e231-461d-bca8-92f97f4f7fd9)

**Comment by alexjustesen** [comment] 2024-08-13 19:22
My bad, I thought you had found a reference somewhere else.

**Comment by mircsicz** [comment] 2024-08-13 20:38
> > I ran the 'docker exec' line like an hour before I posted to this issue 😉
> 
> Doesn't seem that command is listed in the documentation anymore (perhaps it returned inaccurate results?). Docs now tell you to navigate to `https://c.speedtest.net/speedtest-servers-static.php` to view a list of best servers near you. Regardless of all of that, the reason your speedtests aren't working with your current config is because they are no longer valid servers, as determined by Ookla. Use the link provided to get some server ids to edit your config with.

Thanks for the hints, with that it now works as expected...

**Comment by alexjustesen** [comment] 2024-08-13 21:44
Seems like OP is all set as some PRs were merged to address the original issue. Any further issues let's open a new one.

**Closed by alexjustesen** 2024-08-13 21:44 UTC
Labels: 🐛 bug
