### ISSUE TITLE
Cron isse: Want to run every 32 minutes, but runs at top of the hour + top of the hour and 31 minutes.

### ISSUE THREAD

**Issue by fischerphilipp** [alexjustesen/speedtest-tracker#1360] opened 2024-04-08 08:11 UTC
### Discussed in https://github.com/alexjustesen/speedtest-tracker/discussions/1359

<div type='discussions-op-text'>

<sup>Originally posted by **fischerphilipp** April  8, 2024</sup>
Hi Alex,

thanks a lot for creating and maintaining this tool, really helpful for me.

When configuring and adjusting the speedtests I discovered the following:
I initially had the speedtests run at the top of the hour, like 8:00, 9:00 etc. However apparently some speedtest servers are at maximum capacity at that time because I discovered that when there are breaches to the set thresholds, this almost always occurs at the top of the hour. If I move the tests to a little later, then the results are way more consistent and reaching my ISP top speed. 

My current Cron setting is */32 * * * * 
However I have two issues with the tests:
* Although I set it to run at /32 I always also get a test at the the top of the hour. No idea where this is coming from (see screenshot).
* The cron generator you linked says that /32 should let the test run every 32 minutes (which is what I want), instead I see the tests running always at 32 minutes past the hour. Because I want ~two tests within one hour I would prefer it to run as the generator says. Is that an issue with the linked cron generator or with Speedtest tracker?

Thanks in advance and best regards,
Philipp
![Screenshot 2024-04-08 at 10 03 06](https://github.com/alexjustesen/speedtest-tracker/assets/68103956/f992742a-8f0f-4d96-acad-97a34eb58975)
</div>

**Comment by wdog** [comment] 2024-04-08 13:23
`*/32` searches for the 32th minute in the hour starting at the hour ( so in total 2 times ). I think there is no way to do what you want using crontab ( maybe with systemd timers )

https://en.wikipedia.org/wiki/Cron ( slash section ).

**Comment by alexjustesen** [comment] 2024-04-08 15:25
Duplicate of #1359, also take a look at https://github.com/alexjustesen/speedtest-tracker/issues/552#issuecomment-2028532010 and this will help you get started with offset schedules.

**Closed by alexjustesen** 2024-04-08 15:25 UTC

**Comment by fischerphilipp** [comment] 2024-04-08 15:56
Thanks so much. @wdog After you responded and before your added example I also tried this which I could now also verify to work:
28,58 * * * *
However I’m not sure what the difference between your suggestion and mine is. The outcome seems to be similar.
