### ISSUE TITLE
Error 500 on general setting and speedtest not working

### ISSUE THREAD

**Issue by Kunalb963** [alexjustesen/speedtest-tracker#943] opened 2023-11-28 18:42 UTC
I am using container in Synology DS220+ NAS

❌ There seems to be a failure in checking the web server + PHP-FPM. Here's the response:
#14 /var/www/html/vendor/livewire/livewire/src/Features/SupportPageComponents/HandlesPageComponents.php(14): Livewire\\Features\\SupportPageComponents\\SupportPageComponents::interceptTheRenderOfTheComponentAndRetreiveTheLayoutConfiguration()
#24 /var/www/html/vendor/livewire/livewire/src/Features/SupportPageComponents/HandlesPageComponents.php(14): Livewire\\Features\\SupportPageComponents\\SupportPageComponents::interceptTheRenderOfTheComponentAndRetreiveTheLayoutConfiguration()
#34 /var/www/html/vendor/livewire/livewire/src/Features/SupportPageComponents/HandlesPageComponents.php(14): Livewire\\Features\\SupportPageComponents\\SupportPageComponents::interceptTheRenderOfTheComponentAndRetreiveTheLayoutConfiguration()
#44 /var/www/html/vendor/livewire/livewire/src/Features/SupportPageComponents/HandlesPageComponents.php(14): Livewire\\Features\\SupportPageComponents\\SupportPageComponents::interceptTheRenderOfTheComponentAndRetreiveTheLayoutConfiguration()
#54 /var/www/html/vendor/livewire/livewire/src/Features/SupportPageComponents/HandlesPageComponents.php(14): Livewire\\Features\\SupportPageComponents\\SupportPageComponents::interceptTheRenderOfTheComponentAndRetreiveTheLayoutConfiguration()
#64 /var/www/html/vendor/livewire/livewire/src/Features/SupportPageComponents/HandlesPageComponents.php(14): Livewire\\Features\\SupportPageComponents\\SupportPageComponents::interceptTheRenderOfTheComponentAndRetreiveTheLayoutConfiguration()
#74 /var/www/html/vendor/livewire/livewire/src/Features/SupportPageComponents/HandlesPageComponents.php(14): Livewire\\Features\\SupportPageComponents\\SupportPageComponents::interceptTheRenderOfTheComponentAndRetreiveTheLayoutConfiguration()
#84 /var/www/html/vendor/livewire/livewire/src/Features/SupportPageComponents/HandlesPageComponents.php(14): Livewire\\Features\\SupportPageComponents\\SupportPageComponents::interceptTheRenderOfTheComponentAndRetreiveTheLayoutConfiguration()A clear and concise description of what the bug is.

**To Reproduce**
version: '3.3'
services:
    tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 6443:443
        environment:
            - PUID=1026
            - PGID=100
            - APP_KEY=base64:2Sv4krpXu4yspl8lahCiWpafS9U4OqUPWkbrVEm87C4=
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/volume1/docker/speedtest:/config'
            - '/volume1/docker/speedtest/web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mariadb:10
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest_tracker
            - MARIADB_USER=speedy
            - MARIADB_PASSWORD=password
            - MARIADB_RANDOM_ROOT_PASSWORD=true
        volumes:
            - speedtest-db:/var/lib/mysql
volumes:
  speedtest-db:

**Comment by alexjustesen** [comment] 2023-11-28 18:45
It seems to happen pretty randomly, can you restart the container and check if you can access the UI?

If so feel free to close the issue.

**Comment by Kunalb963** [comment] 2023-11-28 19:07
i tried every possible solution even deleted the env file i can only access the ui of all except general setting only.

**Comment by Kunalb963** [comment] 2023-11-28 19:10
> i tried every possible solution even deleted the env file i can only access the ui of all except general setting only.

also no results shown.
![image](https://github.com/alexjustesen/speedtest-tracker/assets/129251751/c8c3f24e-876d-4167-a07e-928f48d0d637)

**Comment by alexjustesen** [comment] 2023-11-28 21:48
> > i tried every possible solution even deleted the env file i can only access the ui of all except general setting only.
> 
> also no results shown.
> 

Do you want to keep your data or are you ok with starting over?

**Comment by Kunalb963** [comment] 2023-11-29 06:52
> php artisan app:install --force

done but still same issue.

**Comment by alexjustesen** [comment] 2023-11-29 12:32
Can you attach a copy of the log? Should start from line 1.

**Comment by Kunalb963** [comment] 2023-11-29 17:53
> Can you attach a copy of the log? Should start from line 1.

🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...
🐇  Configuring Speedtest Tracker...
🔒  Fixing app path file permissions...
✅  Permissions fixed.
🧹  Clearing any previous caches...
✅  Cache cleared.
✅  Environment file exists.
🔗  Creating symlinks for config and log files...
✅  Symlinks created.
✅  An application key environment variable exists.
💰  Building the cache...
✅  Cache set.
🚛  Migrating the database...
✅  Database migrated.
✅  All set, Speedtest Tracker started.
[27-Nov-2023 22:51:14] NOTICE: fpm is running, pid 119
[27-Nov-2023 22:51:14] NOTICE: ready to handle connections
[27-Nov-2023 22:51:14] NOTICE: systemd monitor interval set to 10000ms
❌ There seems to be a failure in checking the web server + PHP-FPM. Here's the response:
172.19.0.1 - - [27/Nov/2023:22:51:32 +0530] "GET / HTTP/2.0" 200 4890 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
172.19.0.1 - - [27/Nov/2023:22:51:40 +0530] "GET /admin HTTP/2.0" 200 12459 "https://192.168.2.0:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
172.19.0.1 - - [27/Nov/2023:22:51:43 +0530] "GET /livewire/livewire.js?id=2b77c128 HTTP/2.0" 200 69756 "https://192.168.2.0:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
172.19.0.1 - - [27/Nov/2023:22:51:45 +0530] "POST /livewire/update HTTP/2.0" 200 5075 "https://192.168.2.0:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
172.19.0.1 - - [27/Nov/2023:22:52:22 +0530] "POST /livewire/update HTTP/2.0" 200 2694 "https://192.168.2.0:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
172.19.0.1 - - [27/Nov/2023:22:52:24 +0530] "POST /livewire/update HTTP/2.0" 200 1735 "https://192.168.2.0:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
172.19.0.1 - - [27/Nov/2023:22:52:31 +0530] "GET /admin/results HTTP/2.0" 200 20487 "https://192.168.2.0:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
172.19.0.1 - - [27/Nov/2023:22:52:32 +0530] "POST /livewire/update HTTP/2.0" 200 2883 "https://192.168.2.0:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
172.19.0.1 - - [27/Nov/2023:22:53:43 +0530] "GET /admin HTTP/2.0" 200 12457 "https://192.168.2.0:8443/admin/results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
172.19.0.1 - - [27/Nov/2023:22:53:45 +0530] "POST /livewire/update HTTP/2.0" 200 3111 "https://192.168.2.0:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
172.19.0.1 - - [27/Nov/2023:22:53:48 +0530] "POST /livewire/update HTTP/2.0" 200 2641 "https://192.168.2.0:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
172.19.0.1 - - [27/Nov/2023:22:53:49 +0530] "GET /admin/results HTTP/2.0" 200 20890 "https://192.168.2.0:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
172.19.0.1 - - [27/Nov/2023:22:53:56 +0530] "GET /admin HTTP/2.0" 200 12476 "https://192.168.2.0:8443/admin/results" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
172.19.0.1 - - [27/Nov/2023:22:53:58 +0530] "POST /livewire/update HTTP/2.0" 200 3093 "https://192.168.2.0:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
172.19.0.1 - - [27/Nov/2023:22:54:03 +0530] "GET / HTTP/2.0" 200 4905 "https://192.168.2.0:8443/admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"

**Comment by alexjustesen** [comment] 2023-11-29 18:03
Just to confirm you can access and sign into the application at `/admin` and it's just the general settings page throwing the 500 error?

**Comment by Kunalb963** [comment] 2023-11-29 19:20
> Just to confirm you can access and sign into the application at `/admin` and it's just the general settings page throwing the 500 error?

yes. can you take over to my device to setup new container build to help me out and if you want to contact me plese send me the email to 963kunal.biswas@gmail.com

**Comment by fluidsc** [comment] 2023-11-29 20:02
This same issue popped up for me over the past couple of days...not sure exactly when. The command listed above (php artisan app:install --force) to force a reset of the application has it working again. Just wanted to make that known since I literally just had the 500 status error start for me randomly without me changing anything related to the container.

**Comment by Kunalb963** [comment] 2023-11-29 20:11
> This same issue popped up for me over the past couple of days...not sure exactly when. The command listed above (php artisan app:install --force) to force a reset of the application has it working again. Just wanted to make that known since I literally just had the 500 status error start for me randomly without me changing anything related to the container.

php artisan app:install --force) it also did not work for me.

**Comment by alexjustesen** [comment] 2023-11-29 20:19
I bet this is tied to the recent introduction of the public dashboard setting and potentially a migration that didn't run. I'll look into it tonight.

**Comment by Kunalb963** [comment] 2023-11-29 20:32
> I bet this is tied to the recent introduction of the public dashboard setting and potentially a migration that didn't run. I'll look into it tonight.

update us as soon as it resolved

**Comment by Minirex96** [comment] 2023-11-30 04:38
Just wanted to add that I'm also getting this 500 error since the lastest update. Can't access the docker container at all.

**Comment by alexjustesen** [comment] 2023-12-02 15:09
@Kunalb963 can you dump the settings table from the app's database and attach it as a csv file to this issue? You can connect and dump the database using an application like DBeaver if you're not familiar with working with databases.

**Comment by alexjustesen** [comment] 2023-12-04 15:44
> Also running in to this 500 error for the last few weeks now

Do you mind also dumping your `settings` table?

**Comment by alexjustesen** [comment] 2023-12-04 16:13
> This is probably way more info than you need but I am on Unraid and wasn't sure where to pull the docker config

I was actually looking for the `settings` database table

**Comment by Bulletoverload** [comment] 2023-12-04 16:15
> > This is probably way more info than you need but I am on Unraid and wasn't sure where to pull the docker config
> 
> I was actually looking for the `settings` database table

Sorry, where do I grab that from?

**Comment by crypticviper** [comment] 2023-12-05 10:36
I have identical issue. Below is my settings table export (had to redact my email id)

my HW is different. Running on Rpi4 Open Media Vault 6 Docker container

https://pastebin.com/raw/YdZJpweb

**Comment by alexjustesen** [comment] 2023-12-05 12:02
> I have identical issue. I have exported the "settings" table into csv and attached here (had to remove my email id). Hope that helps.
> 
> My HW is different. Running on Rpi4, Open Media Vault. Docker image is the latest. I have auto update of docker images setup so that may have caused it to fetch an image that has this issue.
> 
> [settings.zip](https://github.com/alexjustesen/speedtest-tracker/files/13551210/settings.zip)

Thank you, for a while now there's been some random settings only issues cropping up and it's been a PITA to debug

**Comment by alexjustesen** [comment] 2023-12-08 00:21
@crypticviper are you comfortable manually updating a record? If so can you change your timezone from `Europe\/Berlin` to `Europe/Berlin` and let me know if that fixes the issue?

**Comment by alexjustesen** [comment] 2023-12-08 01:40
@Kunalb963 @Bulletoverload if y'all can dump your `settings` table from the speedtest database please do so.

**Comment by alexjustesen** [comment] 2023-12-08 03:10
> I don't have access to the app at all. Where can I grab the settings table at? I'm on Unraid
> 

Are you using sqlite or MySQL for a database?

**Comment by Minirex96** [comment] 2023-12-08 03:22
Can confirm... the Unraid setup uses sqlite
![image](https://github.com/alexjustesen/speedtest-tracker/assets/152466183/1753aabc-a0b9-4f64-ac57-3f2529a36c80)

**Comment by Minirex96** [comment] 2023-12-08 04:25
My logs...

[07-Dec-2023 23:20:53] NOTICE: fpm is running, pid 111
[07-Dec-2023 23:20:53] NOTICE: ready to handle connections
[07-Dec-2023 23:20:53] NOTICE: systemd monitor interval set to 10000ms

🐇  Configuring Speedtest Tracker...

🔒  Fixing app path file permissions...
✅  Permissions fixed.

🧹  Clearing any previous caches...
✅  Cache cleared.

🔗  Creating database symlink...
✅  Database symlink created.

✅  Environment file exists.

🔗  Creating symlinks for config and log files...
✅  Symlinks created.

✅  An application key exists.

💰  Building the cache...
✅  Cache set.

🚛  Migrating the database...
✅  Database migrated.

✅  All set, Speedtest Tracker started.

usermod: no changes

--------------------------------------------------------------------

 _______                       __ __                __
|     __|.-----.-----.-----.--|  |  |_.-----.-----.|  |_
|__     ||  _  |  -__|  -__|  _  |   _|  -__|__ --||   _|
|_______||   __|_____|_____|_____|____|_____|_____||____|
         |__|
 _______                   __
|_     _|.----.---.-.----.|  |--.-----.----.
  |   |  |   _|  _  |  __||    <|  -__|   _|
  |___|  |__| |___._|____||__|__|_____|__|


--------------------------------------------------------------------

To support Speedtest Tracker visit:
https://github.com/alexjustesen/speedtest-tracker
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

🔒 SSL_MODE has been set to MIXED, setting the web server to work in HTTP + HTTPS...

🐇  Configuring Speedtest Tracker...

🔒  Fixing app path file permissions...
✅  Permissions fixed.

🧹  Clearing any previous caches...
✅  Cache cleared.

🔗  Creating database symlink...
✅  Database symlink created.

✅  Environment file exists.

🔗  Creating symlinks for config and log files...
✅  Symlinks created.

✅  An application key exists.

💰  Building the cache...
✅  Cache set.

🚛  Migrating the database...
✅  Database migrated.

✅  All set, Speedtest Tracker started.

[2023-12-08 04:21:32] production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(77): tap()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(60): Illuminate\\Encryption\\EncryptionServiceProvider->key()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\\Encryption\\EncryptionServiceProvider->parseKey()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(955): Illuminate\\Container\\Container->resolve()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(940): Illuminate\\Container\\Container->make()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\\Foundation\\Application->make()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(982): Illuminate\\Container\\Container->resolveClass()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(943): Illuminate\\Container\\Container->resolveDependencies()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(955): Illuminate\\Container\\Container->resolve()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(940): Illuminate\\Container\\Container->make()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(169): Illuminate\\Foundation\\Application->make()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#24 /var/www/html/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#43 /var/www/html/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#44 {main}
"} 
192.168.2.98 - - [07/Dec/2023:23:21:32 -0500] "GET / HTTP/2.0" 500 6609 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0"
[2023-12-08 04:21:32] production.ERROR: No application encryption key has been specified. {"exception":"[object] (Illuminate\\Encryption\\MissingAppKeyException(code: 0): No application encryption key has been specified. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:79)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(77): tap()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(60): Illuminate\\Encryption\\EncryptionServiceProvider->key()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(32): Illuminate\\Encryption\\EncryptionServiceProvider->parseKey()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(908): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(955): Illuminate\\Container\\Container->resolve()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(940): Illuminate\\Container\\Container->make()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1066): Illuminate\\Foundation\\Application->make()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(982): Illuminate\\Container\\Container->resolveClass()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(943): Illuminate\\Container\\Container->resolveDependencies()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(955): Illuminate\\Container\\Container->resolve()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(940): Illuminate\\Container\\Container->make()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(255): Illuminate\\Foundation\\Application->make()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(213): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware()
#18 /var/www/html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->terminate()
#19 {main}
"}

**Comment by parallax-home** [comment] 2023-12-08 12:04
As a brand new user I just did a completely fresh install on a new VM/Docker from the docker-compose in the instructions using Postgres, and after entering the default user/password it returns me to the "getting started" screen. Clicking on the "sign in / admin panel" link again returns me to the "getting started" screen. I am unable to proceed and have never got to the main screen.

There's no error in the logs for either the db container or the main app, but a few restarts ago I got the "There seems to be a failure in checking the web server + PHP-FPM. Here's the response:" error from the first post. I ran `php artisan app:install --force` and that fixed the problem.

Again, this was a completely new install - I've never run this program before.

Ubuntu 23.10
Docker 24.0.7

**Comment by alexjustesen** [comment] 2023-12-08 12:21
> As a brand new user I just did a completely fresh install on a new VM/Docker from the docker-compose in the instructions using Postgres, and after entering the default user/password it returns me to the "getting started" screen. Clicking on the "sign in / admin panel" link again returns me to the "getting started" screen. I am unable to proceed and have never got to the main screen.
> 

This has been fixed in a beta build, just click for the admin panel again. 

> There's no error in the logs for either the db container or the main app, but a few restarts ago I got the "There seems to be a failure in checking the web server + PHP-FPM. Here's the response:" error from the first post. I ran `php artisan app:install --force` and that fixed the problem.
> 
> Again, this was a completely new install - I've never run this program before.
> 
> Ubuntu 23.10
> Docker 24.0.7

Fpm issues are random and can be ignored. This issue relates to the settings page so if your having other problems please open a separate issue.

**Comment by alexjustesen** [comment] 2023-12-08 12:23
@Minirex96 your error is in the first line of the output. It's asking for an app key which has been covered in other issues and generating one is in the docs. That should solve your issue.

**Comment by crypticviper** [comment] 2023-12-08 12:28
> @crypticviper are you comfortable manually updating a record? If so can you change your timezone from `Europe\/Berlin` to `Europe/Berlin` and let me know if that fixes the issue?

I changed this, restarted the container. Still same issue.

**Comment by Bulletoverload** [comment] 2023-12-08 12:48
> > > @Kunalb963 @Bulletoverload if y'all can dump your `settings` table from the speedtest database please do so.
> > 
> > 
> > I don't have access to the app at all. Where can I grab the settings table at? I'm on Unraid
> 
> On Unraid you can find it in Shares>appdata>speedtest-tracker>database.sqlite. Easiest way is to set the appdata share to export=yes and security=public then navigate over your network to that directory. I followed the instructions above and downloaded DBeaver and connected it to the database file and then exported the settings table to csv as requested. All this was new for me but it wasn't hard to figure out.
> 
> [settings_202312072234.csv](https://github.com/alexjustesen/speedtest-tracker/files/13608582/settings_202312072234.csv)

This was perfect thanks. @alexjustesen Attached is my settings table.

[settings.csv](https://github.com/alexjustesen/speedtest-tracker/files/13614150/settings.csv)

**Comment by alexjustesen** [comment] 2023-12-08 12:52
Yeah formatting of the time zone is wrong again. I'm going to make a cli command to fix settings manually.

**Comment by Bulletoverload** [comment] 2023-12-08 13:05
I changed the timezone entry to "America/New_York", restarted the container and confirmed the change stuck, but still getting the error.

**Comment by alexjustesen** [comment] 2023-12-08 13:11
> I changed the timezone entry to "America/New_York", restarted the container and confirmed the change stuck, but still getting the error.

Can you also remove the `null` from within the speedtest servers array?

**Comment by Minirex96** [comment] 2023-12-09 19:08
> @Minirex96 your error is in the first line of the output. It's asking for an app key which has been covered in other issues and generating one is in the docs. That should solve your issue.

Yep fixed it

**Comment by crypticviper** [comment] 2023-12-11 12:41
> > @crypticviper are you comfortable manually updating a record? If so can you change your timezone from `Europe\/Berlin` to `Europe/Berlin` and let me know if that fixes the issue?
> 
> I changed this, restarted the container. Still same issue.

Ok, I had an additional issue of missing app key. Somehow, it was not being read from .env file. So I had to set it in my docker compose file and it started working.

Thanks for your help.

**Comment by alexjustesen** [comment] 2023-12-11 13:51
Closing haven't heard from OP in 2 weeks, feel free to open a new issue if the problem persists.

**Closed by alexjustesen** 2023-12-11 13:51 UTC
Labels: 🐛 bug
