### ISSUE TITLE
No Dashboard Content / Graphs with v0.16.x

### ISSUE THREAD

**Issue by OddSquirrel** [alexjustesen/speedtest-tracker#1175] opened 2024-02-20 01:45 UTC
**Describe the bug**
No data provided on dashboard after migration, although the data is visible under results 

**To Reproduce**
1. Update to v0.16.1
2. Run Migrate in the results section
3. Migration is reported as successful
4. Results table visible
5. Graph missing

**Expected behavior**
The dashboard should show a graph related to the available test results in the database.

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
-  Architecture: amd64
-  Database: PostgreSQL
 - Browser: 6.5.3206.63 (Stable channel) (64-Bit)
 - Version: v0.16.1-v0.16.3

**Screenshots**
![image](https://github.com/alexjustesen/speedtest-tracker/assets/39886438/4e122cab-c9d8-453e-ab1f-5b16ca3988a0)

![image](https://github.com/alexjustesen/speedtest-tracker/assets/39886438/a134b0ed-1a79-4987-8533-6724e47d5588)

**Logs**
Nothing peculiar in the log, no visible error messages.

**Additional context**
This occurs with v0.16.1 and v0.16.3. Could not try with v0.16.2 because I could not pull it.
EDIT: Probably did pull v0.16.2, but the version info contained v0.16.1.

**Comment by AlliedMineral** [comment] 2024-02-20 02:17
Lost all my prior results with 0.16.3 too using MariaDB

**Comment by OddSquirrel** [comment] 2024-02-20 04:16
Thanks for chiming in, @AlliedMineral. Unfortunately, it did not help in my case, but it was a reasonable suggestion.

**Comment by OddSquirrel** [comment] 2024-02-20 04:29
Just noticed that all the relevant results' states show `failed`, even though they certainly have not. Maybe that prevents them from being shown in the graph.

**Comment by alexjustesen** [comment] 2024-02-20 12:09
Regarding the failed status, are you guys running postgres? #1177 seems to be the root cause of this issue.

**Comment by alexjustesen** [comment] 2024-02-20 13:08
Tonight I'm going to create a maintenance job that you can trigger from the cli, this will check for the existence of `download` and `upload` values in the table and will correct the status to `completed`.

**Comment by alexjustesen** [comment] 2024-02-21 01:59
#1197 will be in the next release later tonight. If this doesn't fix the status issue tag me and we'll reopen the issue.

**Closed** 2024-02-21 02:02 UTC
Labels: 🐛 bug

**Comment by OddSquirrel** [comment] 2024-02-21 17:06
> Tonight I'm going to create a maintenance job that you can trigger from the cli, this will check for the existence of `download` and `upload` values in the table and will correct the status to `completed`.

@alexjustesen, are you referring to this: `app:fix-result-statuses`? If so, I tried to run it, but the following is all I got:

![image](https://github.com/alexjustesen/speedtest-tracker/assets/39886438/e6b7feab-5f62-4f41-b1bd-28ce87bc74f7)

Am I possibly doing something wrong? 🤔

**Comment by OddSquirrel** [comment] 2024-02-21 17:29
And that worked a treat, thank you! 😀 Was I simply being an idiot? Just asking because that prefix wasn't mentioned anywhere in the docs, but maybe it's really common knowledge.

**Comment by alexjustesen** [comment] 2024-02-21 17:44
I rewrote the page yesterday and completely forgot to include the prefix. I am indeed the moron here.

**Comment by OddSquirrel** [comment] 2024-02-21 23:06
Meh, no worries. You're putting out so many fires at breakneck speed, I have no idea how you manage to keep it all together in the first place. All is well, I really appreciate your help.

**Comment by alexjustesen** [comment] 2024-02-22 00:17
> Meh, no worries. You're putting out so many fires at breakneck speed, I have no idea how you manage to keep it all together in the first place. All is well, I really appreciate your help.

Me either man, I've got a full time job, freelance clients, a saas I'm launching in April and married with kid. I need 30h days.

**Comment by OddSquirrel** [comment] 2024-02-22 00:56
I hear you on those 30h days. No kids, but self-employed with impatient clients and trying to juggle it all like a madman. 🙈
