### ISSUE TITLE
Time / Server ID Bug

### ISSUE THREAD

**Issue by MrNoooooooob** [alexjustesen/speedtest-tracker#1605] opened 2024-07-13 19:15 UTC
The time and server ID don't work and can't be set. Is it correct as I have entered it?

services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            - 8080:80
            - 8443:443
        environment:
            - PUID=504
            - PGID=20
            - APP_KEY=Key
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=speedy
            - DB_PASSWORD=password
            - OOKLA_EULA_GDPR=true 
            - SPEEDTEST_SCHEDULE=5 */7 * * *
            - SPEEDTEST_SERVERS=30906
            - PRUNE_RESULTS_OLDER_THAN=true 
            - CHART_DATETIME_FORMAT=d.m.Y H:i
            - DATETIME_FORMAT=d.m.Y H:i
            - TZ=Europe/Berlin
            - APP_TIMEZONE=Europe/Berlin
            - DISPLAY_TIMEZONE=Europe/Berlin
        volumes:

**Comment by svenvg93** [comment] 2024-07-15 21:38
Can you elaborate on why you think it’s not possible? Is there a error in the application or does something not work as expected. 

With the time do you mean the timezone or the time format.

**Comment by MrNoooooooob** [comment] 2024-07-15 21:50
because it doesn't run the cron and shows me the wrong time and doesn't select the server ID that I have stored.

Are the settings stored there correct or is there still '' or brackets ()?

**Comment by svenvg93** [comment] 2024-07-16 14:10
As it’s only a partial compose it’s hard to pin point the problem.
I assume that you now redacted the APP_KEY. And that your database is reachable, volumes are specified as needed. The only one I have set between brackets is the two DATETIME_FORMAT ones.


side note;
- OOKLA_EULA_GDPR is not needed 
- PRUNE_RESULTS_OLDER_THAN true is not a valid value it should a number for days older then will be deleted.

**Comment by alexjustesen** [comment] 2024-07-17 12:56
> * PRUNE_RESULTS_OLDER_THAN true is not a valid value it should a number for days older then will be deleted.

This might be the root cause of the issue, also make sure to restart the container when config values are changed. If this still doesn't work open a terminal session into the container and follow these steps:

1. `cd /app/www`
2. run `php artisan optimize` to refresh the cache
3. restart the container again

**Comment by MrNoooooooob** [comment] 2024-07-17 20:50
Thank You, functions! :-)

**Comment by svenvg93** [comment] 2024-07-30 12:07
@MrNoooooooob Please close the issue if the problem is solved :)

**Closed** 2024-07-30 12:11 UTC
