### ISSUE TITLE
Exported time/date incorrect in CSV

### ISSUE THREAD

**Issue by damienbutt** [alexjustesen/speedtest-tracker#1373] opened 2024-04-12 18:24 UTC
**Describe the bug**
The dates in the exported CSV are incorrect. The dates are correct on the dashboard. But in the exported CSV, the date is always `07.06.1975`. 

**To Reproduce**
1. Export data
2. Open CSV and check "createdAt" column

**Expected behavior**
Exported CSV to display correct timestamp with date and time.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
-  Architecture: amd64
 - Browser Firefox
 - Version v124.0.2

**Comment by alexjustesen** [comment] 2024-04-13 13:47
I couldn't reproduce this one, while it doesn't take into account the timezone maybe it has to do with your formatting if you're opening it in Excel?

![image](https://github.com/alexjustesen/speedtest-tracker/assets/1144087/127cfcb1-f09a-42c9-b532-0cd41648474e)

**Comment by damienbutt** [comment] 2024-04-13 14:29
Hi,

Actually you’re correct. My apologies.

If I open the file in Excel it has the correct date/time. And also if I open the file in a text editor the date/time is correct. I should have checked that before posting. 

I generally use OnlyOffice and opening the CSV in the spreadsheets in OnlyOffice is where the date/time is wrong. Must be an issue on their side.

Thanks,
D

**Comment by damienbutt** [comment] 2024-04-13 14:50
Also just checked with Google Sheets and it's formatted correctly there too.

Strange as never had problems with OnlyOffice before.

**Comment by alexjustesen** [comment] 2024-04-14 03:33
Thanks for confirming man. I'll close this ticket.

**Closed** 2024-04-14 03:33 UTC
Labels: 🐛 bug
