### ISSUE TITLE
docker installation

### ISSUE THREAD

**Issue by rob-1981** [alexjustesen/speedtest-tracker#197] opened 2022-12-11 08:48 UTC
Hello,
I'm using DSM and i would like to run speedtest-tracker on docker. Do you have a docker installation ?

**Comment by mztiq** [comment] 2022-12-11 12:22
Heya,

yes there is, check the documentation: https://docs.speedtest-tracker.dev/getting-started/installation

**Comment by ks2018ks** [comment] 2022-12-12 13:32
I tried to to follow these instructions but it did not install on Synology

I used synology task scheduler to user script to run this:

```
docker run -d --name speedtest-tracker \
    -p 8080:80 \
    -p 8443:443 \
    -e PUID=1000 \ 
    -e PGID=1000 \
    -v /path/to/directory:/config \
    ghcr.io/alexjustesen/speedtest-tracker:latest
    restart: unless-stopped
```

It gave me: 
```
Current status: 127 (Interrupted)
Standard output/error:
docker: invalid reference format.
See 'docker run --help'.
/bin/bash: line 4: -e: command not found
/bin/bash: line 7: restart:: command not found
```

**Comment by alexjustesen** [comment] 2022-12-16 01:52
@ks2018ks how did you install the container, I couldn't get GHCR as a registry on the DS.

**Comment by alexdelprete** [comment] 2022-12-16 02:46
I highly recomment to use docker-compose on Synology.

**Comment by ks2018ks** [comment] 2022-12-16 09:30
> @ks2018ks how did you install the container, I couldn't get GHCR as a registry on the DS.

I'm not sure that I did.  I tried the script as per your documentation: https://docs.speedtest-tracker.dev/getting-started/installation, and the [post above](https://github.com/alexjustesen/speedtest-tracker/issues/197#issuecomment-1346507053), 

I put your script here into the Synology task scheduler task, changing only the PUID and PGID to match mine, and emailing the outcome to myself

```
docker run -d --name speedtest-tracker \
    -p 8080:80 \
    -p 8443:443 \
    -e PUID=1000 \ 
    -e PGID=1000 \
    -v /path/to/directory:/config \
    ghcr.io/alexjustesen/speedtest-tracker:latest
    restart: unless-stopped
```

When it tried to run the script I got an email from the NAS saying 

```
Current status: 127 (Interrupted)
Standard output/error:
docker: invalid reference format.
See 'docker run --help'.
/bin/bash: line 4: -e: command not found
/bin/bash: line 7: restart:: command not found
```

**Comment by ks2018ks** [comment] 2022-12-16 09:40
> I highly recommend to use docker-compose on Synology.

I couldn't work out how to do that.

Google found me some [step by step instructions for another program](https://linuxhint.com/docker-compose-with-synology/#:~:text=Docker%20Compose%20is%20a%20command,yaml)%20for%20your%20Docker%20projects.), but I struggled to work out what to do with each of the options in the documentation page here:https://docs.speedtest-tracker.dev/getting-started/installation#install-with-docker-compose.  It seems there are options for 3 types of database, but I don't know if they need to be installed first or how to configure them.  I assume once that's done, I'd need to create a  docker-compose.yaml file from one of those options and then run docker-compose up -d from SSH telnet into the NAS?  But would I need to create folders somewhere first?  A separate one for installation and another for running the app/container?  Where will the packages be downloaded?

**Comment by alexjustesen** [comment] 2022-12-20 20:43
@ks2018ks did you make any progress or still stuck?

**Comment by ks2018ks** [comment] 2022-12-20 21:34
Still stuck I'm afraid

**Comment by ks2018ks** [comment] 2022-12-21 10:42
> I highly recommend to use docker-compose on Synology.

@alexdelprete 
Any chance you could explain the steps to a beginner with limited linux know-how

**Comment by alexdelprete** [comment] 2022-12-21 13:47
> Any chance you could explain the steps to a beginner with limited linux know-how

I always try to help when I can, but not if you don't have the minimum idea of what we're talking about. You need to first get the basics first. Please try to at least get the basics of docker, the minimum basic, and then once you have that you'll understand docker compose. If not, I'll be glad to help on docker compose but I need you to first learn the basics of docker.

If you want to use these kind of services/apps, docker is a mandatory "class".

Let me know when you're ready and I'll be glad to help.

**Comment by mztiq** [comment] 2022-12-21 14:22
> I tried to to follow these instructions but it did not install on Synology
> 
> I used synology task scheduler to user script to run this:
> 
> ```
> docker run -d --name speedtest-tracker \
>     -p 8080:80 \
>     -p 8443:443 \
>     -e PUID=1000 \ 
>     -e PGID=1000 \
>     -v /path/to/directory:/config \
>     ghcr.io/alexjustesen/speedtest-tracker:latest
>     restart: unless-stopped
> ```
> 
> It gave me:
> 
> ```
> Current status: 127 (Interrupted)
> Standard output/error:
> docker: invalid reference format.
> See 'docker run --help'.
> /bin/bash: line 4: -e: command not found
> /bin/bash: line 7: restart:: command not found
> ```

I never used `docker compose` on my Synology NAS, but I think your  `docker run` syntax simply is wrong (at least for your use case with Synology).  
You could start by removing `-e PUID=1000` and `-e PGID=1000` and I think changing `restart: unless-stopped` to `--restart= unless-stopped`.  
You could also install Portainer on your NAS to make things more user-friendly, Portainer lets you use `docker compose` in its Stacks. See [this tutorial](https://mariushosting.com/synology-30-second-portainer-install-using-task-scheduler-docker/) on how to set up Portainer on your Synology NAS.  

In the end I agree with @alexdelprete though, you should really spend some time and try to understand how things work, thats the only way you can run your environment securely. It's not only about "getting things to work".  
Don't take this as harsh critizism, more as a friendly hint.

**Comment by alexdelprete** [comment] 2022-12-21 14:23
> I have 3 docker apps successfully installed and running including Unifi controller, but in each case, there were helpful step-by-step instructions given

Instructions for docker and docker-compose example file have been provided, they're more than enough even for the casual user. If you want to use docker, you should know what docker is, otherwise you won't be able to do anything if you have problems with a docker app.

> surely it is in their interests to write a few more words explaining exactly how to install their work, so that it gets the maximum installed user base

so you think it is possible to have a monkey installing docker and a docker app? I don't think so. Users (like me), in my personal view, have to have a minimum basic understanding of what is docker, a docker volume mapping, a port, etc. if they want to use docker apps. This is the open-source world, it's not a software you buy and pretend a step-by-step manual for dummies.

If you don't have interest in learning at least the very basic of docker, etc. and don't want to spend your valuable time, don't pretend that other people would spend their time helping you just because you don't want to do it.

If you use Synology packages, ask the community there to create a package for Speedtest-Tracker, so with a couple of clicks even you will be able to install it.

> I am not a developer and therefore have little interest in applications development or detailed learning of linux, databases, etc.

I'm not a developer either, and many people that use docker aren't, docker is not about developing.

> It would be helpful to know the answers to those questions at least.

The questions asked show how you have absolutely zero knowledge of docker, etc. That's why answering is impossible, you wouldn't be able to understand the answers. If you spent 1h of your time studying the basics of docker (plenty of video guides on this if you don't like reading), instead of 1h of your time writing in this issue thread, you wouldn't ask those questions and you would have ST up and running.

Cheers.

**Comment by ks2018ks** [comment] 2022-12-21 14:30
> > so you think it is possible to have a monkey installing docker and a docker app? 
Well perhaps I'm not even a monkey, but I managed to install [that app](https://registry.hub.docker.com/r/jacobalberty/unifi/) with the steps described.  It's clear you've take offensive, where none is intended, but likewise you could've probably answered the questions/listed the steps quicker than trolling me for not being as interested in docker than you.  I'll move on and out of your way.

**Comment by mztiq** [comment] 2022-12-21 15:20
@ks2018ks did you see my answer?  
Don't let this end with a fight where no fight was intended. Stick to it **especially** when you encounter some problems, try to solve them and try learning new things. This should be the essence of this discussion, and I'm sure that's what Alex meant.  
Don't take things too personal, I'm sure you can get ST to run on your Syno, you're almost there ;-).  

Sorry for using this as some kind of "private convo"  but I've no idea how to reach @ks2018ks elsewhere.  
My Blog is linked in my GitHub profile, there you'll find ways to contact me if you want to reach out.

**Comment by alexdelprete** [comment] 2022-12-21 19:30
> Don't let this end with a fight where no fight was intended. Stick to it **especially** when you encounter some problems, try to solve them and try learning new things. This should be the essence of this discussion, and I'm sure that's what Alex meant.

Amen.

**Comment by alexjustesen** [comment] 2022-12-21 19:48
I added an Issue on the docs repo for when I get back to my homelab to get solid directions written up for installing and configuring Speedtest Tracker on a Synology device. Progress can be followed here: https://github.com/alexjustesen/speedtest-tracker-docs/issues/6

**Comment by mztiq** [comment] 2022-12-21 20:35
Just tried it out with my Synology NAS and created https://github.com/alexjustesen/speedtest-tracker-docs/pull/7 as a first draft for documentation.

**Comment by alexjustesen** [comment] 2023-01-04 03:15
@rob-1981 and @mztiq I've got the image publishing to Docker Hub now which means you can install it through the Synology DSM UI. Just search for `alexjustesen/speedtest-tracker` and it should show up in the results. Additionally the only thing I changed was the port mapping to available ports and mapped a local volume to `/config`.

Give it a try and let me know how it works for you.

![image](https://user-images.githubusercontent.com/1144087/210477669-6a1552d5-dc82-4dbc-8bda-de2c8595629d.png)

**Comment by mztiq** [comment] 2023-01-04 04:03
Worked fine for me, updated the Installation Instructions accordingly (https://github.com/alexjustesen/speedtest-tracker-docs/pull/7).

**Comment by alexjustesen** [comment] 2023-01-04 04:09
Thanks, now that this is easier and documented I'm closing this out.

**Closed by alexjustesen** 2023-01-04 04:09 UTC
Labels: 📖 documentation, docker
